# Generated by Django 4.0.1 on 2022-01-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='text',
            field=models.TextField(),
        ),
    ]
