# Generated by Django 4.0.1 on 2022-01-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_cartao_loja_transacao_alter_parser_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='loja',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='uploads.loja'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
    ]
