# Generated by Django 4.0.1 on 2022-01-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_transacao_loja_alter_transacao_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='loja',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='uploads.loja'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='numero',
            field=models.CharField(default='', max_length=12),
        ),
    ]
