# Generated by Django 4.0.1 on 2022-01-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_cartao_loja_alter_cartao_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.FloatField(),
        ),
    ]
