# Generated by Django 4.0.1 on 2022-01-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_alter_transacao_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parser',
            options={'managed': False},
        ),
    ]
