# Generated by Django 4.0.1 on 2022-01-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_alter_parser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parser',
            options={},
        ),
    ]
