# Generated by Django 4.0.1 on 2022-01-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_alter_parser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='cpf',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
    ]
